WordPressCom-Stats-iOS/StatsTableViewController.m
WordPressCom-Stats-iOS/WPStatsService.h
WordPressCom-Stats-iOS/WPStatsService.m
WordPressCom-Stats-iOS/WPStatsServiceRemote.h
WordPressCom-Stats-iOS/WPStatsServiceRemote.m
WordPressCom-Stats-iOSTests/WPStatsServiceTests.m

Closes #67 
Shows a section with posts during the time period selected.  Still need to determine if counts are appropriate/necessary for this section but that can be resolved in the design review.

Show posts made during a certain time period

---

StatsDemo/StatsDemo/WPSViewController.h
StatsDemo/StatsDemo/WPSViewController.m
WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
WordPressCom-Stats-iOS/SiteStats.storyboard
WordPressCom-Stats-iOS/StatsTableViewController.m
WordPressCom-Stats-iOS/WPStatsViewController.h
WordPressCom-Stats-iOS/WPStatsViewController.m

Closes #114 
Also limit the selection style color for rows that aren't selectable.

Implement launch URL when one exists

---

WordPressCom-Stats-iOS/WPStatsService.m

Closes #121 
This gets us a bit closer to the Moment.js date age calculation logic. There could be additional tweaking for rounding of days and hours but this is good enough for now.
Ultimately this age should be coming from the backend when we support localizing the API calls.

Improved date age calculation

---

StatsDemo/StatsDemo/StatsDemo Internal-Info.plist
StatsDemo/StatsDemo/StatsDemo-Info.plist
StatsDemo/StatsDemo/WPSAppDelegate.m

Added WPiOS styling to StatsDemo

---

WordPressCom-Stats-iOS/SiteStats.storyboard
WordPressCom-Stats-iOS/WPStatsGraphBackgroundView.m
WordPressCom-Stats-iOS/WPStatsGraphBarCell.m
WordPressCom-Stats-iOS/WPStatsGraphViewController.m

Move y-axis labels to the right and reduce to 3 labels

---

WordPressCom-Stats-iOS/SiteStats.storyboard
WordPressCom-Stats-iOS/StatsTableViewController.m
WordPressCom-Stats-iOS/WPStatsGraphBackgroundView.m
WordPressCom-Stats-iOS/WPStatsGraphBarCell.m
WordPressCom-Stats-iOS/WPStatsGraphViewController.m
WordPressCom-Stats-iOS/WPStatsServiceRemote.m

Closes: #138 
Prerequisite: #140

Update graph styles

---

StatsDemo/StatsDemo/StatsDemo Internal-Info.plist
WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
WordPressCom-Stats-iOS/SiteStats.storyboard
WordPressCom-Stats-iOS/StatsDateUtilities.h
WordPressCom-Stats-iOS/StatsDateUtilities.m
WordPressCom-Stats-iOS/StatsTableViewController.m
WordPressCom-Stats-iOS/WPStatsService.m
WordPressCom-Stats-iOSTests/StatsDateUtilitiesTests.m

Closes #145 
Added a period header for the current period and date.

Added a period header under the graph like the web version

---

StatsDemo/StatsDemo/StatsDemo Internal-Info.plist
WordPressCom-Stats-iOS/SiteStats.storyboard
WordPressCom-Stats-iOS/StatsSelectableTableViewCell.h
WordPressCom-Stats-iOS/StatsSelectableTableViewCell.m
WordPressCom-Stats-iOS/StatsTableViewController.m
WordPressCom-Stats-iOS/StatsTwoColumnTableViewCell.h
WordPressCom-Stats-iOS/StatsTwoColumnTableViewCell.m
WordPressCom-Stats-iOS/StatsViewAllTableViewController.m
WordPressCom-Stats-iOS/WPStatsGraphBarCell.m
WordPressCom-Stats-iOS/WPStatsGraphViewController.m
WordPressCom-Stats-iOS/WPStyleGuide+Stats.h
WordPressCom-Stats-iOS/WPStyleGuide+Stats.m

Closes #150 
The app is nowhere near complete but this is a first good release.

Final design tweaks for 0.2.0 release

---

WordPressCom-Stats-iOS/WPStatsGraphBarCell.m

Closes #189 
Check for selected state inside of setHighlighted and set color of the bar accordingly.

Add condition for selected state in setHighlighted

---

Podfile
Podfile.lock
StatsDemo/Podfile.lock
WordPressCom-Stats-iOS.podspec

Fix for this #193 
cc @astralbodies, please review.

Update pod versions.

---

WordPressCom-Stats-iOS/SiteStats.storyboard
WordPressCom-Stats-iOS/StatsViewAllTableViewController.m

Fixes #197 
Copied the missing logic from View All from the main table. Eventually this will be encapsulated entirely in the cell class so that it isn't duplicated.

Fixes view all not rendering properly for nested cells

---

README.md
StatsDemo/StatsDemo/Base.lproj/Main_iPad.storyboard
StatsDemo/StatsDemo/Base.lproj/Main_iPhone.storyboard

Update README and launch instructions

---

Podfile
Podfile.lock
WordPressCom-Stats-iOS.podspec

Updates podspec to 0.2.2. Uses shared pod v0.3

---

WordPressCom-Stats-iOS.podspec

Fix dependency version. Bumps to version 0.2.3

---

WordPressCom-Stats-iOS/SiteStats.storyboard

This PR sets the storyboardID  for `StatsViewAllTableViewController` entities.
/cc @astralbodies

Adds Stats View All storyboardID

---

WordPressCom-Stats-iOS/SiteStats.storyboard

Adds Storyboard ID to StatsPostDetailsTableViewController scene.

---

WordPressCom-Stats-iOS.podspec
WordPressCom-Stats-iOS/StatsPostDetailsTableViewController.m
WordPressCom-Stats-iOS/StatsTableViewController.m
WordPressCom-Stats-iOS/StatsViewAllTableViewController.m

Borrow the AFNetworking macro to prevent compilation error in today ext

---

WordPressCom-Stats-iOS/WPStatsServiceRemote.m

Date/time format fix to HH:MM AM

---

WordPressCom-Stats-iOS/SiteStats.storyboard

Fixes #293 
Had Today Stats visitors on Insights mis-wired in the Storyboard for the 2x2 layout. Value is now properly updating.

Didn't have the visitors value button wired up.

---

WordPressCom-Stats-iOS.podspec
WordPressCom-Stats-iOS/SiteStats.storyboard

Fixes #308 
Properly wires up the segmented control (again) to the selector on the view controller. Not really sure how this was broken...

Fixed segmented control not firing & updated frame

---

WordPressCom-Stats-iOS/WPStatsServiceRemote.m

See http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/
Needs Review: @astralbodies

Fix imports so it can be built as a framework

---

WordPressCom-Stats-iOS.podspec
WordPressCom-Stats-iOS/Services/WPStatsServiceRemote.m
WordPressCom-Stats-iOS/UI/InsightsTableViewController.m
WordPressCom-Stats-iOS/UI/StatsPostDetailsTableViewController.m
WordPressCom-Stats-iOS/UI/StatsSelectableTableViewCell.m
WordPressCom-Stats-iOS/UI/StatsTableViewController.m
WordPressCom-Stats-iOS/UI/StatsTwoColumnTableViewCell.m
WordPressCom-Stats-iOS/UI/WPFontManager+Stats.h
WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.h
WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.m

Reverts wordpress-mobile/WordPressCom-Stats-iOS#344

Revert 8b591f3059707b91a39a3879036f84c05cffbad5

---

Podfile
Podfile.lock
StatsDemo/Podfile.lock
WordPressCom-Stats-iOS.podspec
WordPressCom-Stats-iOS/WordPressCom-Stats-iOS-Prefix.pch

Refs wordpress-mobile/WordPress-iOS#4371
WPiOS PR: wordpress-mobile/WordPress-iOS#4522
Needs Review: @diegoreymendez

Update to CocoaLumberjack 2.2.0

---

WordPressCom-Stats-iOS/UI/InsightsTableViewController.m

Closes #372 
Order has been updated:
Needs Review: @jancavan, @jleandroperez

Updated order of Insights to latest

---

WordPressCom-Stats-iOS/UI/SiteStats.storyboard

h/t to @kurzee and @frosty for the assistance on resolving these errors/warnings.
Testing: 
1. Open the Storyboard in Xcode 7.3.
2. Bask in its warningless glory.
3. Profit.
Needs Review: @kurzee

Resolves Xcode 7.3 Storyboard warnings

---

.travis.yml
Podfile
Podfile.lock
StatsDemo/Podfile
StatsDemo/Podfile.lock
StatsDemo/StatsDemo.xcodeproj/project.pbxproj
WordPressCom-Stats-iOS.xcodeproj/project.pbxproj

Closes #407 
Updated configuration to the latest for CocoaPods 1.0. 
Testing:
1. Build and Test the main project.
2. Build and run the StatsDemo project.
Needs Review: @kwonye

Update to CocoaPods 1.0

---

WordPressCom-Stats-iOS/UI/WPStatsViewController.h
WordPressCom-Stats-iOS/UI/WPStatsViewController.m

A prerequisite for wordpress-mobile/WordPress-iOS#5590
Needs review: @bummytime

Adding the ability to get stats service from the delegate
