wordpress-mobile/WordPressCom-Stats-iOS

- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/StatsEphemory.h
- WordPressCom-Stats-iOS/StatsEphemory.m
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/WPStatsService.h
- WordPressCom-Stats-iOS/WPStatsService.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.h
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
- WordPressCom-Stats-iOSTests/StatsEphemoryTests.m
- WordPressCom-Stats-iOSTests/WPStatsServiceTests.m
Closes #15 
Adds a basic caching mechanism to the WPStatsService. I chose to include the cache `StatsEphemory` at the service layer because it's a form of a persistence mechanism. The implementation detail should not be part of the view controller. I feel like there is room for improvement over the way I've implemented it but it's a simple solution to start with.
At some point having a layer in front of the service makes sense because it can cache stats for multiple sites and persist beyond the somewhat disposable instance of `WPStatsService`.
Pull to refresh forces the cache to evict all items as it's a user-requested force refresh. Tapping between periods and dates will not force a refresh.
cc: @jleandroperez
> Basic caching with time-based expiration

- WordPressCom-Stats-iOS/StatsTableViewController.m
Closes #14 
Change the leading edge constraint to multiple 7 points for each level of an item. It's subtle but useful. Also firmed up logic for picking the right constraint.
> Indents table rows when appropriate

- StatsDemo/StatsDemo.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/WPStatsGraphViewController.h
- WordPressCom-Stats-iOS/WPStatsGraphViewController.m
- WordPressCom-Stats-iOS/WPStatsService.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
Closes #112 
Fixes some problems with the table refresh animation (in both iOS 7 and 8) and also alignment warnings with autolayout in iOS 7.  Also snuck in a change to prevent the graph from being tapped on while a download is occurring.  I added the network indicator to show there is something happening but there needs to be a better user experience for a downloading state.
> Fixes for iOS 7 in layout, etc

- WordPressCom-Stats-iOS/StatsSummary.h
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/WPStatsGraphViewController.h
- WordPressCom-Stats-iOS/WPStatsGraphViewController.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
Resolves #122 
When the values for a particular period had a comma (or period depending on locale) the graph bars wouldn't always render properly. The numeric value is needed for bar calculation so `StatsSummary` was updated to include the original non-localized value.  This should resolve a lot of the weirdness seen in the graph rendering.
> Graph bars didn't always load properly

- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/WPStatsService.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.h
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
Closes #124 
Don't block the UI during fetch - instead cancel pending remote operations. If the data is fully cached for a particular date/period then display the results. If there is an incomplete result set cached then refetch the entire result.
> Don't block the UI during fetch

- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsTableViewController.h
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/WPStatsContainerViewController.h
- WordPressCom-Stats-iOS/WPStatsContainerViewController.m
- WordPressCom-Stats-iOS/WPStatsViewController.m
Closes #133 
Stats table view now scrolls underneath the `UISegmentedControl`.
> Switched Storyboard to containment and pinned period switcher to top

- StatsDemo/StatsDemo/StatsDemo Internal-Info.plist
- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsSelectableTableViewCell.h
- WordPressCom-Stats-iOS/StatsSelectableTableViewCell.m
- WordPressCom-Stats-iOS/StatsTableSectionHeaderView.h
- WordPressCom-Stats-iOS/StatsTableSectionHeaderView.m
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/WPStatsGraphBarCell.m
- WordPressCom-Stats-iOS/WPStyleGuide+Stats.h
- WordPressCom-Stats-iOS/WPStyleGuide+Stats.m
Closes #139 & #143 
Adds a bunch of styling changes to the rows below the graph.
> Styling below graph

- Podfile.lock
- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsBorderedCellBackgroundView.h
- WordPressCom-Stats-iOS/StatsBorderedCellBackgroundView.m
- WordPressCom-Stats-iOS/StatsGroup.h
- WordPressCom-Stats-iOS/StatsGroup.m
- WordPressCom-Stats-iOS/StatsSection.h
- WordPressCom-Stats-iOS/StatsSelectableTableViewCell.m
- WordPressCom-Stats-iOS/StatsStandardBorderedTableViewCell.h
- WordPressCom-Stats-iOS/StatsStandardBorderedTableViewCell.m
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/StatsTwoColumnTableViewCell.h
- WordPressCom-Stats-iOS/StatsTwoColumnTableViewCell.m
- WordPressCom-Stats-iOS/StatsViewAllTableViewController.h
- WordPressCom-Stats-iOS/StatsViewAllTableViewController.m
- WordPressCom-Stats-iOS/WPStatsService.h
- WordPressCom-Stats-iOS/WPStatsService.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.h
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
Closes #116 
Implements View All for posts, referrers, clicks, countries, videos and followers. Also made a few architectural improvements with StatsGroup and code reuse between the original stats view controller and the view all controller. More work could be done to share additional logic but this is a decent first attempt. :smile:
> Implement View All

- WordPressCom-Stats-iOS/StatsTableViewController.m
Fixes #156 
Used the wrong section number when storing selected subsections in the dictionary.
> Fixed subsection selections

- Podfile.lock
- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsSection.h
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/WPStatsViewController.h
Closes #148 #152 
Tracks events for the WPAnalytics plug in and also implements the "View Web Version" for temporary use until feature complete.
> Add new Mixpanel events and View Web Version

- .gitignore
- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/StatsBorderedCellBackgroundView.m
- WordPressCom-Stats-iOS/StatsStandardBorderedTableViewCell.h
- WordPressCom-Stats-iOS/StatsTableSectionHeaderView.m
Fixes #159 
A combination of bad conditional math for iPad devices and not resetting some properties on cell reuse caused the extremely bad way section bordered were rendered. Cleaned up the logic and add cell reuse resets. Also made sure all of the cells inherit `WPTableViewCell` so the margins are adjusted properly on the iPad.
> Table section borders working properly on iPad

- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsBorderedCellBackgroundView.h
- WordPressCom-Stats-iOS/StatsBorderedCellBackgroundView.m
- WordPressCom-Stats-iOS/StatsStandardBorderedTableViewCell.h
- WordPressCom-Stats-iOS/StatsStandardBorderedTableViewCell.m
- WordPressCom-Stats-iOS/StatsTableViewController.m
Closes #168 
Added a conditional property to allow the bottom border (cell divider) to be eliminated when needed. By default the border is enabled which was the behavior prior to this change.
After:
cc: @jancavan
> Added property to disable the bottom border on cells

- WordPressCom-Stats-iOS/StatsTwoColumnTableViewCell.m
Closes #166
Makes the left table in the two column cells WordPress blue when it's selectable. I did not change the color on the View All cell as there is a disclosure indicator accessory view (the chevron on the right) to indicate the row is tappable. Eventually when there is a post details view this should probably get revisited for iOS compatibility rather than the web anchor coloring paradigm we're following.
cc: @jancavan
> Change left label when its selectable

- WordPressCom-Stats-iOS/StatsTwoColumnTableViewCell.m
Fixes #164 
Corrects the indentation logic for cells that are nestable.
cc:@jancavan
> Fix the indent for nestable rows

- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/StatsTwoColumnTableViewCell.h
- WordPressCom-Stats-iOS/StatsTwoColumnTableViewCell.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
- WordPressCom-Stats-iOSTests/WPStatsServiceRemoteTests.m
- WordPressCom-Stats-iOSTests/stats-v1.1-country-views-day.json
Closes #167 
1. Switch to Mystery Man for authors/commenters where a Gravatar doesn't exist.
2. Switch to flat flag icons.
3. Override Gravatar icon sizes to be 60px. Image view frame is 20x20 so while this wastes data on non-retina devices, it keeps the image looking nice on up to 3x devices.
cc: @jancavan
> Switch to Gravatar mystery man & rounded icons for authors

- WordPressCom-Stats-iOS/WPStatsGraphBarCell.m
- WordPressCom-Stats-iOS/WPStyleGuide+Stats.m
Closes #173 
Made axis label font 12pt instead of 8pt and adjust the font size up to 50% if the text doesn't fit in the frame.
> Adjust font size of graph bar axis label to be larger

- WordPressCom-Stats-iOS/StatsBorderedCellBackgroundView.h
- WordPressCom-Stats-iOS/StatsBorderedCellBackgroundView.m
- WordPressCom-Stats-iOS/StatsStandardBorderedTableViewCell.h
- WordPressCom-Stats-iOS/StatsStandardBorderedTableViewCell.m
- WordPressCom-Stats-iOS/StatsTwoColumnTableViewCell.m
- WordPressCom-Stats-iOS/WPStyleGuide+Stats.h
- WordPressCom-Stats-iOS/WPStyleGuide+Stats.m
Closes #163 
There is the double coloring on the lines but I think it's fine for this first release. It's not terribly fugly at least :smile: 
cc: @jancavan
> Expanded rows now get a dark border treatment

- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsTableViewController.h
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/WPStatsViewController.h
- WordPressCom-Stats-iOS/WPStatsViewController.m
Closes #165 
Added a floating activity loading indicator for the entire table. It somewhat mimics what's on Android but it's not the most visually appealing. Good enough for now; lets revisit to something more elegant.
> Loading indicator for entire table

- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsTableViewController.m
Closes #184 
This PR is based off the 182-default-messages-branch (by accident). Merge after #183.
cc: @daniloercoli
> Fixed label alignments when left label is blank

- WordPressCom-Stats-iOS/StatsTableViewController.m
Closes #182 
Updated case statement to explicitly define error message for each section. This will also then result in a compiler warning when new sections are defined and not included in the logic.
cc: @daniloercoli for review
> Updated no data messages for three sections

- WordPressCom-Stats-iOS/WPStatsGraphBackgroundView.m
- WordPressCom-Stats-iOS/WPStyleGuide+Stats.h
- WordPressCom-Stats-iOS/WPStyleGuide+Stats.m
Closes #180 
1. Removed y-axis labels during a `drawRect:` to prevent subviews from being added over and over and over and over. This isn't terribly efficient so it should be addressed in the future when adding in the value change animations for the bars.
2. Reduced font size for y-axis labels back to what it was before #173.
3. Fixed y-axis label size so that font can be reduced in the case where the number is too large.
cc: @jancavan
> De-janked Y-Axis Labels 

- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/StatsTwoColumnTableViewCell.h
- WordPressCom-Stats-iOS/StatsTwoColumnTableViewCell.m
Closes #179 
Makes the indentation on expandable cells optional and by default turn off the behavior.
> Remove indentation from cells that are nested

- WordPressCom-Stats-iOS/StatsDateUtilities.h
- WordPressCom-Stats-iOS/StatsDateUtilities.m
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/WPStatsService.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
Closes #181 #186 
Device and site timezones are being mixed up and in some cases not being used when dates are being calculated for end dates and passing dates to remote calls. Site timezone should be used in a very limited manner - really only for determining "today".
The other problem fixed was the individual "View All" calls were not calculating the end date to pass to the service and instead using the begin date.
> Properly calculate dates without mixing timezones

- StatsDemo/StatsDemo/Base.lproj/Main_iPad.storyboard
- WordPressCom-Stats-iOS/StatsDateUtilities.h
- WordPressCom-Stats-iOS/StatsDateUtilities.m
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/WPStatsService.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
- WordPressCom-Stats-iOSTests/WPStatsServiceRemoteTests.m
- WordPressCom-Stats-iOSTests/WPStatsServiceTests.m
Closes #195 
Site timezone is now only used for calculating what "today" is, as it did in the old version of stats. With this PR and the WPiOS blog timezone fix it should resolve any crazy dates and data that doesn't match.
cc: @daniloercoli for review (even after its merged)
> Clarified how dates are used - site time zone is really limited now

- WordPressCom-Stats-iOS/StatsTableViewController.m
Fixes #186 
Reset the selected date to the most recent when the app returns from the background. This isn't the final solution but one that at least fixes the weird behavior with the graph going back in time.
cc: @daniloercoli
> Resolves the issue with the graph changing dates when put in background

- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
- WordPressCom-Stats-iOSTests/WPStatsServiceRemoteTests.m
- WordPressCom-Stats-iOSTests/stats-v1.1-top-posts-day-exception.json
Closes #203 
Use the safe expectation method stringForKey to ensure a string is returned. Ideally the API call should be fixed.
> Safely retrieve string for href in top-posts

- WordPressCom-Stats-iOS/StatsDateUtilities.m
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
- WordPressCom-Stats-iOSTests/StatsDateUtilitiesTests.m
Closes #129 
1. Re-enables events/published items section.
2. Fixes the date parameters sent to the /posts endpoint to include time in the ISO format we all love.
3. Internally establish 23:59:59 for the time on all calculated end dates.
cc: @nbradbury since you originally reported the strangeness
> Re-enable Events/Published section and fix weirdness

- WordPressCom-Stats-iOS/StatsDateUtilities.m
- WordPressCom-Stats-iOS/StatsGroup.m
- WordPressCom-Stats-iOS/StatsSection.h
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/StatsViewAllTableViewController.m
- WordPressCom-Stats-iOS/WPStatsService.h
- WordPressCom-Stats-iOS/WPStatsService.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.h
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
- WordPressCom-Stats-iOSTests/StatsDateUtilitiesTests.m
- WordPressCom-Stats-iOSTests/WPStatsServiceTests.m
Closes #154 #117 
Added sections for search terms and authors. Reordered all the sections to match the current order on single column mode in web stats.
cc: @daniloercoli
> Implement authors and search terms sections

- WordPressCom-Stats-iOS/StatsTableViewController.m
Fixes #210 
Deselects the row for "View Web Version" after the select action happens. 
Good catch @aerych!
> Deselect the View Web Version row after tapping

- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
- WordPressCom-Stats-iOSTests/WPStatsServiceRemoteTests.m
Fixes #212 
Adds `StatsAction`s to tags and categories so they're tappable/reviewable in the app.
props to @daniloercoli
> Add actions (URLs) to tags/categories

- StatsDemo/StatsDemo/WPSAppDelegate.m
- WordPressCom-Stats-iOS/SiteStats.storyboard
Fixes #221 
Sets the font to Open Sans on `UISegmentedControl` instances as well as cells with the empty state. The `UISegmentedControl` tweak is an appearance API adjustment in the StatsDemo app which means WPiOS will need a similar adjustment. Opened issue https://github.com/wordpress-mobile/WordPress-iOS/issues/3385 to track.
> Replace instances of Helvetica with OpenSans

- WordPressCom-Stats-iOS/WPStatsGraphViewController.m
Fixes #123 
I removed the call in the graph view controller that manually hit the delegate method to indicate an item was selected. I'm not really certain why this was here in the first place, possibly as a workaround for a different bug that was solved.
Wil need to make sure we test this one with backgrounding the app, rotating, then foregrounding it. Also test on iPad and iPhone devices. Make sure to include iOS 7 with at least one device as application lifecycle is slightly different between the OSs.
> Do not fire the delegate method for the selected item after a rotate

- WordPressCom-Stats-iOS/SiteStats.storyboard
Set the labels to resize up to 50% in font size and maintain width to
a 8pt space on the left and right. Before we had no constraints on size
just the position. Oopsie poopsie!
Needs Review: @aerych
> Added (forgotten) constraints to most popular day and hour labels.

- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsSelectableTableViewCell.h
- WordPressCom-Stats-iOS/StatsStandardBorderedTableViewCell.h
- WordPressCom-Stats-iOS/StatsTableSectionHeaderView.m
- WordPressCom-Stats-iOS/WPStatsViewController.m
- WordPressCom-Stats-iOSTests/WPStatsServiceRemoteTests.m
Fixes #260 
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/2491
Eliminates the usage of WPTableViewCell which put margins around all the cells in a table view on an iPad.
Needs Review: @aerych
> Stop using WPTableViewCell

- .travis.yml
- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS.podspec
- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/InsightsAllTimeTableViewCell.h
- WordPressCom-Stats-iOS/InsightsAllTimeTableViewCell.m
- WordPressCom-Stats-iOS/InsightsMostPopularTableViewCell.h
- WordPressCom-Stats-iOS/InsightsMostPopularTableViewCell.m
- WordPressCom-Stats-iOS/InsightsSectionHeaderTableViewCell.h
- WordPressCom-Stats-iOS/InsightsSectionHeaderTableViewCell.m
- WordPressCom-Stats-iOS/InsightsTableViewController.m
- WordPressCom-Stats-iOS/InsightsTodaysStatsTableViewCell.h
- WordPressCom-Stats-iOS/InsightsTodaysStatsTableViewCell.m
- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsGroup.m
- WordPressCom-Stats-iOS/StatsSection.h
- WordPressCom-Stats-iOS/StatsTableViewController.m
Closes #264 
On iPhones, show All Time and Today's Stats on Insights in a 2x2 grid rather than a 1x4.
I had a refactor a bunch of the storyboard to move from static cells to dynamic prototypes. This helps pave the way for #257 to be completed easier. I wanted iPhone portrait to be the only size class that got the 2x2 grid but I ran into problems. I time-boxed the solution and the next best solution is 2x2 for all iPhone orientations.
To test, launch StatsDemo after putting a current OAuth2 token and site ID in WPSViewController. Or just use the latest StatsDemo internal release.
Needs Review: @jancavan, @jleandroperez
> Implement Insights 2x2 grid

- StatsDemo/StatsDemo/WPSViewController.m
- WordPressCom-Stats-iOS/SiteStats.storyboard
Fixes #258 
The UINavigationController existed outside of the Storyboard to allow for greater reusability. This is okay on iOS 8 with the new segues (show instead of push) but it breaks things on iOS 7. Readded the nav controller and updated the StatsDemo app to not instantiate another Nav VC.
WPiOS will need to be updated accordingly to support this.
Needs Review: @aerych
> Put the UINavigationController back into the Storyboard to assist iOS 7

- WordPressCom-Stats-iOS/WPStatsService.m
Fixes #265
Don't return data from the local service layer when a remote error exists. This keeps with the design logic of error being passed back with the service object. Only one should be non-nil.
Needs Review: @koke
> Don't set an insights object when there is an error in the remote call

- WordPressCom-Stats-iOS/SiteStats.storyboard
Closes #295 
Added constraints to the segmented control in Insights so that it can't be wider than the screen and also each segment is variably sized. This helps accommodate wider translations of the text. It's not a perfect solution but it does work and makes the UI look less ugly.
Needs Review: @bummytime
> Prevent segmented control from looking horrible

- .travis.yml
- Podfile
- Podfile.lock
- StatsDemo/Podfile.lock
- StatsDemo/StatsDemo.xcodeproj/project.pbxproj
- StatsDemo/StatsDemo.xcodeproj/xcshareddata/xcschemes/StatsDemo Internal.xcscheme
- StatsDemo/StatsDemo.xcodeproj/xcshareddata/xcschemes/StatsDemo.xcscheme
- StatsDemo/StatsDemo/Images.xcassets/AppIcon.appiconset/Contents.json
- StatsDemo/StatsDemo/Images.xcassets/Contents.json
- StatsDemo/StatsDemo/Launch Screen.storyboard
- StatsDemo/StatsDemo/StatsDemo Internal-Info.plist
- StatsDemo/StatsDemo/StatsDemo-Info.plist
- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/InsightsTableViewController.m
- WordPressCom-Stats-iOS/InsightsWrappingTextCell.xib
- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsGroup.m
- WordPressCom-Stats-iOS/StatsLatestPostSummary.h
- WordPressCom-Stats-iOS/StatsLatestPostSummary.m
- WordPressCom-Stats-iOS/StatsSection.h
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/StatsVisits.h
- WordPressCom-Stats-iOS/WPStatsService.h
- WordPressCom-Stats-iOS/WPStatsService.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.h
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
Closes #289 
New UI:
**Test scenarios:**
1. No data.
2. Slow/crappy data (using link conditioner).
3. iPad and iPhone - ensure rotations work right.
4. Sites with no posts.
5. iOS 9, 8 and 7 (I'll take care of most of this).
**How to test:**
* Local deployment if you're into Xcode 7.
* StatsDemo which I'll be sending out soon.
Needs Review: @jancavan, @jleandroperez, @daniloercoli
> Implements latest post summary in Insights

- .travis.yml
- Podfile
- Podfile.lock
- StatsDemo/Podfile.lock
- StatsDemo/StatsDemo.xcodeproj/project.pbxproj
- StatsDemo/StatsDemo.xcodeproj/xcshareddata/xcschemes/StatsDemo Internal.xcscheme
- StatsDemo/StatsDemo.xcodeproj/xcshareddata/xcschemes/StatsDemo.xcscheme
- StatsDemo/StatsDemo/Images.xcassets/AppIcon.appiconset/Contents.json
- StatsDemo/StatsDemo/Images.xcassets/Contents.json
- StatsDemo/StatsDemo/Launch Screen.storyboard
- StatsDemo/StatsDemo/StatsDemo Internal-Info.plist
- StatsDemo/StatsDemo/StatsDemo-Info.plist
- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/InsightsTableViewController.m
- WordPressCom-Stats-iOS/InsightsWrappingTextCell.xib
- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsGroup.m
- WordPressCom-Stats-iOS/StatsLatestPostSummary.h
- WordPressCom-Stats-iOS/StatsLatestPostSummary.m
- WordPressCom-Stats-iOS/StatsSection.h
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/StatsVisits.h
- WordPressCom-Stats-iOS/WPStatsService.h
- WordPressCom-Stats-iOS/WPStatsService.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.h
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
- WordPressCom-Stats-iOS/WPStatsViewController.m
Closes #309 
Persists the last selected "tab" (segment) in stats and defaults it to Insights like before. This tab will be persisted across the sites - so if the user switches sites the last tab will be still selected. Chances are the user will want to come back to the same tab in every site they have.
Needs Review: @jleandroperez 
Do not merge this PR until #315 is merged (this branch is based off of it)
> Persist last selected tab in stats

- StatsDemo/Podfile.lock
- StatsDemo/StatsDemo/StatsDemo Internal-Info.plist
- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/InsightsTableViewController.m
- WordPressCom-Stats-iOS/InsightsWrappingTextCell.xib
- WordPressCom-Stats-iOS/SiteStats.storyboard
- WordPressCom-Stats-iOS/StatsPostDetailsTableViewController.m
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/UIViewController+SizeClass.h
- WordPressCom-Stats-iOS/UIViewController+SizeClass.m
- WordPressCom-Stats-iOS/WPStatsService.h
- WordPressCom-Stats-iOS/WPStatsService.m
- WordPressCom-Stats-iOS/WPStatsServiceRemote.h
- WordPressCom-Stats-iOS/WPStatsServiceRemote.m
- WordPressCom-Stats-iOS/WPStatsViewController.m
- WordPressCom-Stats-iOS/WordPressCom-Stats-iOS-Prefix.pch
- WordPressCom-Stats-iOSTests/StatsDateUtilitiesTests.m
- WordPressCom-Stats-iOSTests/StatsEphemoryTests.m
- WordPressCom-Stats-iOSTests/StatsGroupTests.m
- WordPressCom-Stats-iOSTests/StatsItemTests.m
- WordPressCom-Stats-iOSTests/WPStatsServiceRemoteTests.m
- WordPressCom-Stats-iOSTests/WPStatsServiceTests.m
Closes #316
Recreation of #320 
Removes all usage of IS_IPAD in preference of size classes except where not available (in iOS 7). Also pulled all of the UI-level logic out of the service layer and model objects. Views are now properly resized when size classes change.
Caveats:
1. Portrait and landscape iOS devices smaller than the iPhone 6S are all considered compact. This has implications on the segmented control that I'm not entirely happy with. I may wish to override the behavior of size classes in this case for landscape.
2. The number of bars still needs a bit of work. The number of bars is not refreshed automatically when switching between full screen on the iPad with the multitasking side view. I'm opening a separate issue to deal with this.
Testing:
1. Multitasking on iPad Air and …
> Removes all IS_IPAD references to better support iOS 9

- WordPressCom-Stats-iOS/InsightsTableViewController.m
- WordPressCom-Stats-iOS/StatsPostDetailsTableViewController.m
- WordPressCom-Stats-iOS/StatsTableViewController.m
- WordPressCom-Stats-iOS/StatsViewAllTableViewController.m
Fixes: #335
In the four table view controllers use a weak self reference in all of the completion blocks passed to service calls. This should help prevent crashes when remote calls finish after the view is dismissed and a table animation exception is thrown.
This is a little hard to review with StatsDemo due to the nature of stats being the root view controller. In reality, the best way to test is to point WPiOS at the local directory on your disk:
```
pod 'WordPressCom-Stats-iOS', :path => '../WordPressCom-Stats-iOS/'
```
Needs Review: @koke
> Use weak self references in service completion blocks

- WordPressCom-Stats-iOS.podspec
- WordPressCom-Stats-iOS/Services/WPStatsServiceRemote.m
- WordPressCom-Stats-iOS/UI/InsightsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsPostDetailsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsSelectableTableViewCell.m
- WordPressCom-Stats-iOS/UI/StatsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsTwoColumnTableViewCell.m
- WordPressCom-Stats-iOS/UI/WPFontManager+Stats.h
- WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.h
- WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.m
See https://github.com/wordpress-mobile/WordPress-iOS/issues/4434
Depends on merging and releasing new pods:
- https://github.com/wordpress-mobile/WordPressCom-Analytics-iOS/pull/39
- https://github.com/wordpress-mobile/WordPress-Shared-iOS/pull/81
> Updated WordPressShared and WordPressComAnalytics imports

- WordPressCom-Stats-iOS/UI/SiteStats.storyboard
Fixes #343 
Set the content compression resistance to low to allow the label to be less stabby.
> Allow the text label to be compressed rather than being a rude label

- Podfile.lock
- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS/Services/WPStatsServiceRemote.m
- WordPressCom-Stats-iOS/UI/InsightsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsPostDetailsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsSelectableTableViewCell.m
- WordPressCom-Stats-iOS/UI/StatsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsTwoColumnTableViewCell.m
- WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.h
- WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.m
- WordPressCom-Stats-iOSTests/WPStatsServiceRemoteTests.m
Brings in fixes for 0.4.11 to get it to compile with last minute changes made to other pods to support frameworks.
Related: #347
> Framework pods fixes

- Podfile
- Podfile.lock
- StatsDemo/Podfile.lock
- StatsDemo/StatsDemo/WPSAppDelegate.m
- WordPressCom-Stats-iOS.podspec
- WordPressCom-Stats-iOS/Services/WPStatsServiceRemote.m
- WordPressCom-Stats-iOS/UI/InsightsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsPostDetailsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsSelectableTableViewCell.m
- WordPressCom-Stats-iOS/UI/StatsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsTwoColumnTableViewCell.m
- WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.h
- WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.m
- WordPressCom-Stats-iOSTests/WPStatsServiceRemoteTests.m
Creates a new version of the stats pod (0.4.12) that pulls in corrected dependency pods that don't rename the header file directories to support frameworks. All dependencies now have been versioned in such a way that won't conflict (minor version bumped instead of patch version).
> Selects new pod versions that revert framework fixes

- Podfile
- Podfile.lock
- StatsDemo/Podfile.lock
- StatsDemo/StatsDemo/WPSAppDelegate.m
- WordPressCom-Stats-iOS.podspec
- WordPressCom-Stats-iOS/Services/WPStatsServiceRemote.m
- WordPressCom-Stats-iOS/UI/InsightsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsPostDetailsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsSelectableTableViewCell.m
- WordPressCom-Stats-iOS/UI/StatsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsTwoColumnTableViewCell.m
- WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.h
- WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.m
- WordPressCom-Stats-iOSTests/WPStatsServiceRemoteTests.m
Includes locking down shared pod to prevent framework fixes from borking compilation upstream.
> Bring master current for 0.4.12

- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS/UI/SiteStats.storyboard
- WordPressCom-Stats-iOS/UI/StatsTableViewController.m
- WordPressCom-Stats-iOS/UI/WPStatsViewController.h
Closes #357 
Removes the delegate method to view web stats and the actual table view cell. 
View Web Stats was never visible in StatsDemo so you'll have to test in WPiOS with a local pod.
Needs Review: @jleandroperez, @daniloercoli
> Removed "View Web Version" from stats table

- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS/UI/SiteStats.storyboard
Fixes #362 
Not quite exactly sure how this happened but the segue used to connect the period-based stats rows (daily, monthly, weekly, yearly) with the post details screen was missing. This also happened in Insights to another segue and was fixed.
Testing:
1. Using StatsDemo (or point a local WPiOS Podfile at this checked out branch on disk using `path => '~/path/to/stats'`.
2. Go into a period-based stats screen.
3. Tap the different rows to see if they load properly. This includes expanding collapsed rows, View All, etc. Make sure they all work the way they should.
> Replaced the missing segue on main stats table to load post details

- WordPressCom-Stats-iOS/Services/WPStatsService.h
- WordPressCom-Stats-iOS/Services/WPStatsService.m
- WordPressCom-Stats-iOS/Services/WPStatsServiceRemote.h
- WordPressCom-Stats-iOS/Services/WPStatsServiceRemote.m
- WordPressCom-Stats-iOS/UI/StatsPostDetailsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsTableViewController.m
- WordPressCom-Stats-iOS/UI/UIViewController+SizeClass.m
- WordPressCom-Stats-iOS/UI/WPStatsGraphViewController.h
- WordPressCom-Stats-iOS/UI/WPStatsGraphViewController.m
- WordPressCom-Stats-iOSTests/WPStatsServiceRemoteTests.m
- WordPressCom-Stats-iOSTests/WPStatsServiceTests.m
Fixes: #364
Fixes: #332 
Updated the data behind the graph to be filtered by the graph view controller instead of in the remote service layer. 12 days are picked by default for all remote calls and that data is cached accordingly. When the view controller orientation changes, the data is then truncated for display purposes only. This allows the graph to be refreshed often without expiring the cache or causing a visual delay.
Also fixed with this PR is a problem with the current date selected. If a date was selected in the graph in the past, then view a post detail or view all was tapped, when coming back the graph was redrawn with that date in the past being the most current date selectable. This PR detaches the logic for selected date from the graph being refreshed.
**Testing**
In order …
> Simplifies data behind graph to fix a bug and improve multitasking

- StatsDemo/StatsDemo.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/Services/WPStatsServiceRemote.m
- WordPressCom-Stats-iOS/UI/InsightsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsPostDetailsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsViewAllTableViewController.m
Fixes #369 
Adds `blog_id` and `post_id` to WPAnalytics calls where appropriate. The blog ID is always available and post ID is available when looking at post details.
I also removed some duplicate calls for tracking of view all and post details.
cc: @martinremy
Needs Review: @sendhil, @daniloercoli
> Adds blog and post ID to stats analytics tracking

- WordPressCom-Stats-iOS/UI/WPStatsViewController.m
Fixes #374 
Make sure the presented view controller isn't nil before calling dismissViewController. Comparing two nils is true in the case of stats VC being presented modaly after selecting the blog in the today widget in WPiOS.
Needs Review: @aerych
> Do a nil check on self.presentedViewController before dismissing

- WordPressCom-Stats-iOS/UI/SiteStats.storyboard
Fixes #373
Adds additional layout constraints to prevent the labels from sizing themselves off the screen. In the case of the section label, I set the label to show an ellipsis if there is too much text. I could scale the font but I felt the weird size was more jarring than truncated text.
Needs Review: @jancavan @jleandroperez
> Added additional constraints to prevent labels from going off the screen

- Podfile
- Podfile.lock
- StatsDemo/Podfile.lock
- StatsDemo/StatsDemo/WPSAppDelegate.m
- WordPressCom-Stats-iOS.podspec
- WordPressCom-Stats-iOS/UI/InsightsTableViewController.m
- WordPressCom-Stats-iOS/UI/SiteStats.storyboard
- WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.h
- WordPressCom-Stats-iOS/UI/WPStyleGuide+Stats.m
If it helps testing, this is being used in https://github.com/wordpress-mobile/WordPress-iOS/tree/no-more-open-sans
See: wordpress-mobile/WordPress-iOS#4895
Cc: @mattmiklic 
Needs Review: @astralbodies
> Replace Open Sans with system fonts

- StatsDemo/Podfile.lock
- StatsDemo/StatsDemo/WPSAppDelegate.m
- WordPressCom-Stats-iOS.podspec
- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/Common/WPStatsLogging.h
- WordPressCom-Stats-iOS/Common/WPStatsLogging.m
- WordPressCom-Stats-iOS/WordPressCom-Stats-iOS-Prefix.pch
Based on #391
Previously we defined ddLogLevel as a static variable in the prefix file.
This declares it to every file in the pod but it means that we're stuck with
the default (const) value even if the app setting is different.
AFAIK, there's no way we can directly use the app's ddLogLevel as it needs to
be defined when the framework is linked, so the only way to control this is to
turn that const into a variable, and provide a couple of accessor methods.
cc @astralbodies
> Adds support to set log level from outside the pod

- WordPressCom-Stats-iOS/UI/WPStatsGraphViewController.m
Fixes #367 
Rotation now forces re-selection of the cell and recalculation of the number of cells to show.
To Test:
1. Run iPhone 6s Plus or iPad simulator.
2. Rotate the days/weeks/months/years view and make sure the bars animate properly and select the current period.
Needs Review: @bummytime
> Re-selects cell and calculates number of bars after rotation

- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/UI/InsightsTodaysStatsTableViewCell.m
Fixes #393 
Somehow we're picking the wrong images for latest post summary & today's stats in insights for likes and comments. This fixes that typo.
Needs Review: @bummytime
> Picking the right images for latest post summary & today's stats

- WordPressCom-Stats-iOS/UI/InsightsTableViewController.m
Fixes #385 
When Followers has no data (or has an error) properly calculate the number of rows and do not show the section title after the headers.
cc: @jancavan, @bummytime
> If Followers has no data, do not display the section title cell.

- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/UI/InsightsAllTimeTableViewCell.m
- WordPressCom-Stats-iOS/UI/InsightsTableViewController.m
- WordPressCom-Stats-iOS/UI/InsightsTodaysStatsTableViewCell.m
- WordPressCom-Stats-iOS/UI/NSBundle+StatsBundleHelper.h
- WordPressCom-Stats-iOS/UI/NSBundle+StatsBundleHelper.m
- WordPressCom-Stats-iOS/UI/NSObject+StatsBundleHelper.h
- WordPressCom-Stats-iOS/UI/SiteStats.storyboard
- WordPressCom-Stats-iOS/UI/StatsNoResultsRowTableViewCell.xib
- WordPressCom-Stats-iOS/UI/StatsSelectableTableViewCell.m
- WordPressCom-Stats-iOS/UI/StatsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsTwoColumnTableViewCell.m
Fixes #384 
* Updated the styling of the no results cell to match what was requested. 
* Moved the stats bundle helper class extension to NSBundle rather than NSObject. 
* Pulled the no results cell out of the storyboard (used in two view controllers) and put it into a XIB.
* Fixed a root folder problem on the UI group. New files were not being placed into the UI folder on disk.
Needs Review: @bummytime, @jancavan
> Style No Results cell more in line with web stats

- WordPressCom-Stats-iOS.podspec
- WordPressCom-Stats-iOS/Services/WPStatsService.m
- WordPressCom-Stats-iOS/UI/InsightsTableViewController.m
Noticed that the insights stats was meant be cached, but the cache dictionary wasn't being saved.
Fixed that, and also fixed `InsightsTableViewController` to be able to handle when the data returns immediately.
This will be necessary for wordpress-mobile/WordPress-iOS#5537. Isn't very testable alone, until there is code that takes advantage of the caching.
A small one, hope you don't mind looking this over, @astralbodies, since I saw you've worked on a big chunk of this code.
> Add caching for insight stats data

- WordPressCom-Stats-iOS.podspec
Includes:
* Migration to NSURLSession for networking. #414 
* Allow for stats preloading with delegate access to stats service. #413
> Bump stats version for 0.7.2

- WordPressCom-Stats-iOS/UI/WPStatsViewController.h
The nullability warnings in `WPStatsViewController.h` will go silent. 
It was either getting rid of the one `nullable` specifier or adding a bunch of `null_unspecified`. I decided on the former.
How's this look @astralbodies?
> This will quiet those nullability warnings

- Podfile
- Podfile.lock
- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS.podspec
- WordPressCom-Stats-iOS/Services/WPStatsServiceRemote.m
Closes #417 
Updates AFNetworking to version 3.1
- How to test:
- Launch the StatsDemo app
- Test the several sections of the app and see if everything is working ok.
Needs Review: @astralbodies
> Update to AFNetworking to version 3.1

- Podfile.lock
- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS/Services/WPStatsServiceRemote.m
- WordPressCom-Stats-iOS/UI/StatsTableViewController.m
- WordPressCom-Stats-iOS/UI/WPStatsContributionGraph.m
- WordPressCom-Stats-iOS/UI/WPStatsViewController.h
Fixes #419 
Switches to set custom date formats with the `setLocalizedDateFormatFromTemplate` method so format strings are translated properly for different locales. Does not change any date formatters for things interpreting dates from JSON data.
To test:
1. Using StatsDemo (or WPiOS pointing at your local copy of this pod) launch the app with the locale changed to something like Netherlands/Dutch.
2. Verify all dates are localized properly including: Insights posting activity, Days/Weeks/Months/Years graph x-axis labels, header between graph & Posts & Pages.
3. Validate stats data matches the same period in web-based Calypso stats.
> Switch to setLocalizedDateFormatFromTemplate on UI NSDateFormatters

- Podfile
- Podfile.lock
- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS.podspec
Updates WordPress-Shared-iOS dependency to version 0.6.0.
Needs review: @astralbodies
> Update WordPress-Shared-iOS dependency to 0.6.0

- WordPressCom-Stats-iOS/UI/InsightsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsPostDetailsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsTableViewController.m
- WordPressCom-Stats-iOS/UI/StatsViewAllTableViewController.m
- WordPressCom-Stats-iOS/UI/WPStatsGraphViewController.m
Fixes #424 
Corrects a long-standing issue with the app crashing due to a NIB not being registered when the collection view tries loading the views. Registers the custom NIBs and classes first in `viewDidLoad()`. I also updated all of the table view controllers even though we've never seen a crash there.
Testing requires pulling this pod into the main project and using @frosty's UISplitViewController branch to aggravate the issue. I still, to this day, cannot reproduce the issue with the main app or the StatsDemo application.
Needs Review: @frosty
> Register all NIBs and classes in tables and collection views first.

- WordPressCom-Stats-iOS/UI/WPStatsViewController.m
Fixes a crash I was seeing whilst working on the `feature/ipad-splitview-mysites` split view branch of WPiOS. 
When displayed in a split (compact horizontal size class), but not full screen (multitasking), the stats view controller wants to display the "More..." alert controller in a popover instead of an action sheet. 
However, as this configuration hasn't previously been possible in the app, we weren't configuring the popover presentation delegate. This resulted in a crash.
To test:
Run the `feature/ipad-splitview-mysites` branch of WPiOS, with these tweaks to `WPStatsViewController`. Navigate to stats in the multitasking configuration described / shown above, and try tapping on "More...". Ensure that the popover displays correctly and the app doesn't crash.
Needs review: @astralbodies
> WPStatsViewController: Adds popover presentation source

- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS.podspec
- WordPressCom-Stats-iOS/Services/WPStatsService.m
In the working `feature/ipad-splitview-mysites` branch in WPiOS, we ran into a couple of crashes in `InsightsTableViewController`, seemingly when data was loaded and perhaps the VC wasn't yet onscreen. In particular, the app was crashing on calls to `[tableView endUpdates]` in the callbacks for `retrieveInsightsStatsWithAllTimeStatsCompletionHandler...`.
This PR wraps the cached data callbacks in `retrieveInsightsStatsWithAllTimeStatsCompletionHandler...` in a `dispatch_async`, which ensures they're called on the main queue, and also appears to allow `UITableView` to correctly refresh itself.
To test: Use this branch with the iPad Splitview PR on WPiOS, and verify that the Stats crashes no longer occur: https://github.com/wordpress-mobile/WordPress-iOS/pull/5802
Needs review: @kurzee
Ping …
> Fixes a crash in InsightsTableViewController in WPiOS

- Podfile.lock
- StatsDemo/Podfile.lock
- WordPressCom-Stats-iOS.xcodeproj/project.pbxproj
- WordPressCom-Stats-iOS/UI/WPStatsGraphViewController.m
Closes #432 
Added some sanity checks around the size calculation in the graph view controller to prevent crashes. It's not really possible to cause this crash to happen with StatsDemo. You'll need to integrate it into WPiOS with a :path => '' reference to the local pod. Testing that crash is also a bit hard.
I'm okay with this being a code-only PR review.
Needs Review: @kurzee
> Add sanity checks to the graph view controller size calculations.
